# === General Settings ===
WIFI_SSID = "WIFI-SSID"
WIFI_PASSWORD = "WIFI-PW"

# === HTTP Server Settings ===
HTTP_PORT = 80
HTTP_MAX_PENDING_CONN = 5
HTTP_CLIENT_TIMEOUT_S = 10
HTTP_MAX_REQUEST_SIZE = 1024

# === Intervals ===
MAIN_HEARTBEAT_INTERVAL_S = 5
WIFI_RECONNECT_INTERVAL_S = 60

# === Sensor Reading Configurations ===
TEMP_NUM_READINGS = 10
TEMP_READING_INTERVAL_S = 1

DIST_NUM_READINGS = 10
DIST_READING_INTERVAL_S = 1

TURB_NUM_READINGS = 10
TURB_READING_INTERVAL_S = 1

TDS_NUM_READINGS = 10
TDS_READING_INTERVAL_S = 1

# === Sensor Outlier Limits ===
TEMP_OUTLIER_LIMIT = 0.10
DIST_OUTLIER_LIMIT = 0.50
TURB_OUTLIER_LIMIT = 0.20
TDS_OUTLIER_LIMIT = 0.20

# === Sensor Pins ===
ONBOARD_LED_PIN = "LED"
DS18B20_PIN = 18
HCSR04_TRIGGER_PIN = 20
HCSR04_ECHO_PIN = 19
TURBIDITY_ADC_PIN = 26
TDS_ADC_PIN = 27

# === Log/Cache Files ===
FAILURE_LOG_FILE = "failures.log"

print("Configurations loaded from config.py")
