# === General Settings ===
WIFI_SSID = "Suryland"
WIFI_PASSWORD = "AvengersAssemble2020@@"

# === HTTP Server Settings ===
HTTP_PORT = 80
HTTP_MAX_PENDING_CONN = 5
HTTP_CLIENT_TIMEOUT_S = 10
HTTP_MAX_REQUEST_SIZE = 1024

# === Intervals ===
MAIN_HEARTBEAT_INTERVAL_S = 5
WIFI_RECONNECT_INTERVAL_S = 60

# === Sensor Reading Configurations ===
TEMP_NUM_READINGS = 5
TEMP_READING_INTERVAL_S = 1

DIST_NUM_READINGS = 5
DIST_READING_INTERVAL_S = 1

TURB_NUM_READINGS = 5
TURB_READING_INTERVAL_S = 1

TDS_NUM_READINGS = 5
TDS_READING_INTERVAL_S = 1

# === Sensor Pins ===
ONBOARD_LED_PIN = "LED"
DS18B20_PIN = 18
HCSR04_TRIGGER_PIN = 20
HCSR04_ECHO_PIN = 19
TURBIDITY_ADC_PIN = 26
TDS_ADC_PIN = 27

print("Configurations loaded from config.py")
